services:
  mysql:
    image: mysql:8.0
    container_name: mysql-jpaDemo
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: jpaDemo
      MYSQL_USER: jpaDemo
      MYSQL_PASSWORD: jpaDemo1234
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10